version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9091:9091"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROMETHEUS_PORT=9091
    volumes:
      - ./workspaces:/app/workspaces
    depends_on:
      - redis
    networks:
      - roocode-net
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "9092:9092"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PROMETHEUS_PORT=9092
    volumes:
      - ./workspaces:/app/workspaces
    depends_on:
      - redis
    networks:
      - roocode-net
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - roocode-net
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - roocode-net
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=roocode
    networks:
      - roocode-net
volumes:
  redis-data:
  prometheus-data:
  grafana-data:
networks:
  roocode-net:
    driver: bridge
