global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'roocode-api'
    static_configs:
      - targets: ['api:9091']
    metrics_path: /metrics
  - job_name: 'roocode-worker'
    static_configs:
      - targets: ['worker:9092']
    metrics_path: /metrics
