#!/bin/bash
QUEUE_LENGTH=$(redis-cli -h redis llen job_queue)
MIN_REPLICAS=1
MAX_REPLICAS=10
JOBS_PER_WORKER=5
DESIRED_WORKERS=$(( ($QUEUE_LENGTH + $JOBS_PER_WORKER - 1) / $JOBS_PER_WORKER ))
if [ $DESIRED_WORKERS -lt $MIN_REPLICAS ]; then
    DESIRED_WORKERS=$MIN_REPLICAS
fi
if [ $DESIRED_WORKERS -gt $MAX_REPLICAS ]; then
    DESIRED_WORKERS=$MAX_REPLICAS
fi
docker service scale roocode_worker=$DESIRED_WORKERS
